### ISSUE TITLE
Adds support for custom sampler in config

### ISSUE THREAD

**Issue by jcchavezs** [jcchavezs/zipkin-instrumentation-symfony#34]
At the moment there are [predefined samplers](https://github.com/jcchavezs/zipkin-instrumentation-symfony#samplers) supported. If one wants to use a custom sampler, middleware needs to be declared and added manually. Something like this should be supported:
```
zipkin:
  ...
  sampler:
    type: custom_service
    custom_service: "@my_custom_sampler"
```
